### ISSUE TITLE
Map?

### ISSUE THREAD

**Issue by DatOnePlayer** [BurritoAlpaca/MindustryGreen#10]
Playable but no other resources and enemies

**Comment by BurritoAlpaca** [comment]
Sorry, ill get right on that. The mod may not work for a bit but ill try to get a patch out now. I'm working on a few things at the moment.

**Comment by BurritoAlpaca** [comment]
Finally fixed the issue
Thanks for the heads up @DatOnePlayer for notifying me of the problem.
